### ISSUE TITLE
App name changed (refer attached screenshot)

### ISSUE THREAD

**Issue by cranky-pythonista** [forkgram/TelegramAndroid#97]
![Screenshot_20220817-235636_Settings](https://user-images.githubusercontent.com/88152489/185215349-faa448ff-ec91-4165-9a1b-11c3ebc11764.png)
![Screenshot_20220817-231134](https://user-images.githubusercontent.com/88152489/185215367-e24753ca-ce0e-4e99-9186-4671eaf10621.png)

**Comment by cranky-pythonista** [comment]
Tried clearing cache, reinstalling the app, rebooting my phone. Also I tried renaming it in forkgram settings but nothing happened.

**Comment by Vitalii-code** [comment]
I have this error too

**Comment by 31337** [comment]
Same problem. Also this version extremely drains the battery (Pixel 6). Had to install an older version of the app, unfortunately.

**Comment by Vitalii-code** [comment]
![Screenshot_20220819-001121_.png](https://user-images.githubusercontent.com/58048618/185500157-b5ae6411-47d5-4321-9c9b-d1775d91c603.png)The original telegram is even worse for now, and yes this version is working in background all time.

**Comment by kevin0t** [comment]
I think the package name was mistakenly entered in App name field while building this.

**Comment by vagosss** [comment]
The issue persists with version 9.0.

**Comment by linsui** [comment]
Looks like this only happens in F-Droid version. The GitHub apk doesn't have this problem.

**Comment by licaon-kter** [comment]
As expected? https://github.com/Forkgram/TelegramAndroid/blob/dev/TMessagesProj_AppFork/src/main/AndroidManifest.xml#L7

**Comment by cranky-pythonista** [comment]
@linsui Yes the github version worked! Thanks. I'm closing this issue now, hopefully it gets fixed in the next fdroid update.

**Comment by Idesmi** [comment]
The issue is not fixed.

**Comment by johnwuelk** [comment]
Issue still persists as of now. This is specifically annoying when controlling the phone via speech and Google telling me that I need to install the Telegram App.
Is it hard to just change the App name to Telegram and recompile?
**Edit**: Issue only persists with F-Droid apk! The one here on GitHub is fixed!

**Comment by linsui** [comment]
If you know how to fix it please open a PR.
